// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_polymorphic_positions
Rcpp::IntegerVector cpp_polymorphic_positions(Rcpp::NumericMatrix x, const double threshold);
RcppExport SEXP _DR2S_cpp_polymorphic_positions(SEXP xSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_polymorphic_positions(x, threshold));
    return rcpp_result_gen;
END_RCPP
}
// cpp_top2_cols
Rcpp::List cpp_top2_cols(Rcpp::NumericMatrix x);
RcppExport SEXP _DR2S_cpp_top2_cols(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_top2_cols(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_PSDM
NumericMatrix cpp_PSDM(NumericMatrix consMat, NumericMatrix sequences);
RcppExport SEXP _DR2S_cpp_PSDM(SEXP consMatSEXP, SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type consMat(consMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_PSDM(consMat, sequences));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DR2S_cpp_polymorphic_positions", (DL_FUNC) &_DR2S_cpp_polymorphic_positions, 2},
    {"_DR2S_cpp_top2_cols", (DL_FUNC) &_DR2S_cpp_top2_cols, 1},
    {"_DR2S_cpp_PSDM", (DL_FUNC) &_DR2S_cpp_PSDM, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DR2S(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
