// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_hamming
NumericMatrix cpp_hamming(NumericMatrix sequences);
RcppExport SEXP _DR2S_cpp_hamming(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hamming(sequences));
    return rcpp_result_gen;
END_RCPP
}
// cpp_PSDM
NumericMatrix cpp_PSDM(NumericMatrix consMat, NumericMatrix sequences);
RcppExport SEXP _DR2S_cpp_PSDM(SEXP consMatSEXP, SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type consMat(consMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_PSDM(consMat, sequences));
    return rcpp_result_gen;
END_RCPP
}
// cpp_polymorphicPositions
Rcpp::IntegerVector cpp_polymorphicPositions(Rcpp::NumericMatrix x, const double threshold);
RcppExport SEXP _DR2S_cpp_polymorphicPositions(SEXP xSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_polymorphicPositions(x, threshold));
    return rcpp_result_gen;
END_RCPP
}
// cpp_top2Cols
Rcpp::List cpp_top2Cols(Rcpp::NumericMatrix x);
RcppExport SEXP _DR2S_cpp_top2Cols(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_top2Cols(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DR2S_cpp_hamming", (DL_FUNC) &_DR2S_cpp_hamming, 1},
    {"_DR2S_cpp_PSDM", (DL_FUNC) &_DR2S_cpp_PSDM, 2},
    {"_DR2S_cpp_polymorphicPositions", (DL_FUNC) &_DR2S_cpp_polymorphicPositions, 2},
    {"_DR2S_cpp_top2Cols", (DL_FUNC) &_DR2S_cpp_top2Cols, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DR2S(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
