# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_hamming <- function(sequences) {
    .Call('_DR2S_cpp_hamming', PACKAGE = 'DR2S', sequences)
}

cpp_polymorphic_positions <- function(x, threshold) {
    .Call('_DR2S_cpp_polymorphic_positions', PACKAGE = 'DR2S', x, threshold)
}

cpp_top2_cols <- function(x) {
    .Call('_DR2S_cpp_top2_cols', PACKAGE = 'DR2S', x)
}

cpp_PSDM <- function(consMat, sequences) {
    .Call('_DR2S_cpp_PSDM', PACKAGE = 'DR2S', consMat, sequences)
}

